%%% Script that load the data generated by 'batch_submitter.cmd' that
%%% compiles the script 'wgd_on_SiO2.ctl' with different parameters. This
%%% scrit has to be in the folder in whith all al subfolders like '0.1-0.2'
%%% are generated
clear all
close all

%Parameters
%Import the parameters which were simulated
tuple_file = matfile('tuples.mat');
tuples = tuple_file.tuples;

%d = h, w = w2 for double block code
h = tuples(:,1); % heights of the waveguide in units f a
w = tuples(:,2); % widths of the waveguide in units of a

%Loading the data in the different subfolders
%Generates an N x 4 matrix where each row contains the data 
%[h w vg_diff mode_overlap]
N = length(h);
master_data = zeros(N,7);
vel_siv = zeros(N,1);
vel_tel = zeros(N,1);
vg_difference = zeros(N,1);
gvd_1250 = zeros(N,1);
gvd_zerocross = zeros(N,1);
mode_overlap = zeros(N,1);
vg_min_wavelength = zeros(N,1);

%Import the group velocity data
%for each h, we sweep all possible w before moving to next h value
n=0;
for i = 1:N
        n=n+1;
        hname = num2str(h(i));
        wname = num2str(w(i));
                       
        %Calculate group velocity difference (absolute value)
        vg_difference(n) = vg_diff(hname,wname);              
               
        %Calculate the mode overlap
        mode_overlap(n) = overlap_calculator(hname,wname);
        
        %Import the band data
        [freqs, kvals] = band_importer(hname,wname);
        
        %Import the group velocity data
        velocities = velocity_importer(hname,wname);
        
        %Calculate the Vg minima wavelength
        vg_min_wavelength(n) = vg_min(freqs,velocities);
        
        %Calculate the GVD
        [GVD, gvd_1250(n), gvd_zerocross(n)] = gvd_calculator(freqs,velocities);
        
        %Compile all the data together
        master_data(n,:) = [h(i) w(i) vg_difference(n) abs(mode_overlap(n)) ...
            gvd_1250(n) gvd_zerocross(n) vg_min_wavelength(n)];         
end
%Choose what data to plot and save
band_plotter(h,w);
vg_plotter(h,w);
D_plotter(h,w);
master_plotter(master_data);
top_params(master_data,10);

%Save all the outputs
%Save the output variables
%File to write output data to
fid_master_data = fopen('output.txt', 'wt');
fprintf(fid_master_data,'height \t width \t vg_diff \t mode_overlap \t gvd_zerocross (nm) \t vg min wavelength (nm) \n');
formatspec = '%f \t %f \t %f \t %f \t %f \t %f';
for n = 1:N
    fprintf(fid_master_data,formatspec,master_data(n,1),master_data(n,2),master_data(n,3),master_data(n,4),master_data(n,6),master_data(n,7));
    fprintf(fid_master_data,'\n');
end
fclose(fid_master_data);



